# Generated by Django 5.0.4 on 2024-05-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
